# Site settings
title: 
email: langkahdatuak@gmail.com
url: https://fajrialbiruni.github.io
description: "INVESTASI SYARIAH TANDAN BUAH SEGAR (TBS) SAWIT TANPA RIBA!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: langkahdatuak

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: tter.com/fajrialbiruni
  - title: facebook
    url: https://facebook.com/fajri16
  - title: stack-overflow
    url: http://stackoverflow.com/
  - title: bitbucket
    url: http://bitbucket.org/
  - title: github
    url: https://fajrialbiruni.github.io

# Build settings
markdown: kramdown
permalink: pretty
